### ISSUE TITLE
Update setup.py

### ISSUE THREAD

**Issue by smoeinbbp** [lnxpy/hey#10]
### Description

Add package information in setup.py file.

**Comment by lnxpy** [comment]
It (`setup.cfg`) is actually auto-generated via [setup-py-upgrade](https://github.com/asottile/setup-py-upgrade). Would you explain more about what other information you think is needed? :)

**Comment by smoeinbbp** [comment]
yes, you are right, I didn't check `setup.cfg` file. so I'll close this issue.
