### ISSUE TITLE
Change token storing system from bashrc to keyring python library

### ISSUE THREAD

**Issue by sepehrrasooli** [lnxpy/hey#19]
* Hey version:0.3.3
* Python version:3.12
* Operating System:Debian

### Description
By changing the way hey stores tokens, it's security will improve because anyone with access to the user's terminal can find the token by running:
```bash
echo $HEY_TOKEN
```

**Comment by sepehrrasooli** [comment]
@lnxpy  Thank you for assigning this issue to me, I will work on it and submit a PR shorty.

**Comment by lnxpy** [comment]
@sepehrrasooli 😎
