### ISSUE TITLE
Improve error message

### ISSUE THREAD

**Issue by iam-benyamin** [lnxpy/hey#4]
After I installed Hey, I forgot to do authentication, and the error Hey gave me was not attractive.

```
Traceback (most recent call last):
   File "/home/benyamin/.local/bin/hey", line 8, in <module>
     sys.exit(main())
   File "/home/benyamin/.local/lib/python3.10/site-packages/hey/cli.py", line 70, in main
     raise BrokenCredentials(
hey.exceptions.system.BrokenCredentials: Make sure you have set your MINDSDB_EMAIL_ADDRESS and password via --set-password.
```

I suggest that the error text be something like this

To use hey, you need to do the necessary work

1. Register at mindsdb.com
2. Set your email in .bashrc
3. Setting the login password with the corresponding command

**Comment by lnxpy** [comment]
Hey!

Respectfully, I'm inclined to say that the current exception is quite verbose to the end user and showcases the problem very well as described in more detail in the [article](https://imsadra.me/introducing-hey-your-ai-powered-pair-programming-friend) as well. Don't you think so?! :D

Thanks for trying out Hey btw. I appreciate that.

**Comment by iam-benyamin** [comment]
Now that I read the article again, I came to the conclusion that what is now is enough
